### ISSUE TITLE
[error] Command ERROR

### ISSUE THREAD

**Issue by 1guts1** [LenAnderson/SillyTavern-LALib#3]
Since the upgrade to version d2d142c,all commands cannot be used.
<img width="678" alt="屏幕截图 2024-08-18 010545" src="https://github.com/user-attachments/assets/e963c9ee-de34-4efd-87d0-4f986e7d5152">
<img width="371" alt="屏幕截图 2024-08-18 010655" src="https://github.com/user-attachments/assets/f55728c1-07d1-41a2-8817-e1fc4e5db8bd">

**Comment by LenAnderson** [comment]
Check your browser's console for errors. You need to be on ST's staging branch because release lacks some of the exports that LALib uses.
Or roll back the extension to a commit before August 16 until release gets updated.

**Comment by 1guts1** [comment]
> Check your browser's console for errors. You need to be on ST's staging branch because release lacks some of the exports that LALib uses. Or roll back the extension to a commit before August 16 until release gets updated.

Thank you for your suggestion, but where can I find old version

**Comment by LenAnderson** [comment]
"Installing" an extension is just cloning its repository. You can go into your user's extensions directory and check out a specific commit.

**Comment by 1guts1** [comment]
Thank you for your help.
