### ISSUE TITLE
[Question/Clarification] /or command

### ISSUE THREAD

**Issue by drago87** [LenAnderson/SillyTavern-LALib#6]
The description of how to use the /or command is quite fuzzy.
This is what i'm trying to do. is it pissible?

```
/setvar key=list TabbyAPI, Helper, QR Buttons, FHN, Helpers, Character Maker, SillyTavern|
/ife {: /test left={:
				/or {: 
					left={: /test left=list right=FHN rule=in 
					:} 
					right={: /test left=list right=MHN rule=in
					:}
				:}
				:} right=true rule=eq
:}|
/then {: /echo true :}|
/else {: /echo false :}
```

**Comment by LenAnderson** [comment]
/or works much like core's /if and /while (just without the rule=, of course), that's why I kept the left= right= names for the args. Autocomplete tells you that both named args accept either "true" or "false" as a value.

Can't tell you if what you want to do can be done because I can't seem to make sense of what you're code is supposed to do.

**Comment by drago87** [comment]
It will check if the character have the tags FHN or MNH (Accidently used FHN twice have updated it now).
using `/setvar key=list TabbyAPI, Helper, QR Buttons, FHN, Helpers, Character Maker, SillyTavern` just to test it.
but with or wit out FHN or MNH it will run the /else command

**Comment by LenAnderson** [comment]
Look at the details shown in autocomplete for /or, and the examples in the readme. Compare that to your code above. You're not even giving any named arguments to the command, and /or does not take an unnamed one.

**Comment by drago87** [comment]
Sorry for the late reply, was away the whole last week.
This is what i'm trying to do with the ```/or``` but with ```/ife /elseif /else```

```
/setvar key=list TabbyAPI, Helper, QR Buttons, FHN, Helpers, Character Maker, SillyTavern|
/ife {: /test left={{getvar::list}} right=FHN rule=in :}|
	/then {: /echo true:}|
/elseif {: /test left={{getvar::list}} right=MHN rule=in:}|
	/then {: /echo true:}|
/else {: /echo false :}
```

**Comment by drago87** [comment]
@LenAnderson I'm still stuck at this. Do you think you could make an example?

`/or left=true right=false` only tells me that `left=` and `right=` needs a true/false not how i can give them that

unless it is meant to do it like this
```
/setvar key=list TabbyAPI, Helper, QR Buttons, FHN, Helpers, Character Maker, SillyTavern|
/setvar key=a false|
/setvar key=b false|
/ife {: /test left=list right=FHN rule=in:}|
	/then {: /setvar key=a true :}|
/ife {: /test left=list right=MHN rule=in:}|
	/then {: /setvar key=b true :}|

/or left=a right=b|
/echo {{pipe}}
```
which also don't work for me
