### ISSUE TITLE
[Question/Bug] message-on not working on new chat execution

### ISSUE THREAD

**Issue by soboruB** [LenAnderson/SillyTavern-LALib#7]
Hello! I really enjoy using this extension. Could you help me fix this error?
The `message-on` is not working when `executing on new chat`. I'm using this script:

```
/message-on event=click quiet=true callback={:
  /setmesvar key=x mes={: /add {{lastMessageId}} -1 :}() {{lastUserMessage}} |
  /$ take=textContent {{target}} |
  /message-edit message={:/add {{lastMessageId}} -1:}() {{pipe}} | 
  /:delete | 
  /flushvar regex | 
  /flushvar regexflags | 
:} .custom-button |
```
When the chat changes, QR is applied but the `message-listener` remains empty. So I need to manually click QR again to make it work.

Also, may I ask about the script? Before the update, I used:
```
/elseif {: /test left={{getvar::location}} right=house rule=in case=off:} | /then {: /bg house :} |
```
But after the update, I changed it to:
```
/elseif ( 'house' in location ) {: /bg house :}
```

Now it only works with 'house' but not 'House'. I tried to apply regex but I'm not sure how to write the script. 
I attempted something like `/elseif ( /house/i in location) `but it didn't work.
Can you help me with this? Thank you!

**Comment by LenAnderson** [comment]
Message listeners get cleared on chat change. QR receives the chat change event before LALib. -> your new listeners are immediately removed.
Call message-on with fireandforget with a delay of a second or two.

`/house/i == location` should work.

**Comment by soboruB** [comment]
Thank you for your help! It works perfectly now.
